### ISSUE TITLE
Hi, I follow the instruction, and I meet the following errors.

### ISSUE THREAD

**Issue by bobododosjl** [GREAT-WHU/DBA-Fusion#1]
CMake Error at wrap/cmake/PybindWrap.cmake:62 (list):
  list does not recognize sub-command POP_FRONT
Call Stack (most recent call first):
  python/CMakeLists.txt:96 (pybind_wrap)

CMake Error at python/CMakeLists.txt:108 (set_target_properties):
  set_target_properties Can not find target to add properties to: gtsam_py

CMake Error at wrap/cmake/PybindWrap.cmake:62 (list):
  list does not recognize sub-command POP_FRONT
Call Stack (most recent call first):
  python/CMakeLists.txt:175 (pybind_wrap)

CMake Error at python/CMakeLists.txt:187 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  gtsam_unstable_py

**Comment by yuxuanzhou97** [comment]
It looks like a CMake version issue🤔. We use CMake 3.21.5 and Ubuntu 20.04. Updating the CMake version might help.

**Comment by bobododosjl** [comment]
thank u, this problem has been solved, and I want to know the correct version of CUDA,  
RuntimeError: 
The detected CUDA version (12.1) mismatches the version that was used to compile
PyTorch (11.3). Please make sure to use the same CUDA versions.

**Comment by yuxuanzhou97** [comment]
We use torch 1.11.0 + CUDA 11.3 for all  the tests 🙂

**Comment by bobododosjl** [comment]
thanks, I solve the above problems. However, I meet the following error when I execuate python batch_whu.py
Traceback (most recent call last):
  File "/home/sjl-phd/PHD/code/DBA-Fusion/demo_vio_whu.py", line 10, in <module>
    from dbaf import DBAFusion
  File "/home/sjl-phd/PHD/code/DBA-Fusion/dbaf/dbaf.py", line 5, in <module>
    from depth_video import DepthVideo
  File "/home/sjl-phd/PHD/code/DBA-Fusion/dbaf/depth_video.py", line 11, in <module>
    from multi_sensor import MultiSensorState
  File "/home/sjl-phd/PHD/code/DBA-Fusion/dbaf/multi_sensor.py", line 2, in <module>
    import gtsam
  File "/home/sjl-phd/anaconda3/envs/dbaf/lib/python3.10/site-packages/gtsam/__init__.py", line 9, in <module>
    from gtsam import gtsam, utils
ImportError: /home/sjl-phd/PHD/code/gtsam/build/gtsam/libgtsam.so.4: undefined symbol: _ZNSt12experimental10filesystem2v17__cxx114path14_M_split_cmptsEv

**Comment by yuxuanzhou97** [comment]
It looks like a boost issue.🤔 Try "sudo apt-get install libboost-all-dev". Please let me know if it works.🙂

**Comment by bobododosjl** [comment]
problem still exists

**Comment by ZhouTangtang** [comment]
Oh sorry, this is not a boost issue. It seems related to the version of gcc. Try google this error. (I'm just doing so😂)

**Comment by ZhouTangtang** [comment]
Oh sorry, this is not a boost issue. It seems related to the support of c++17. Try google "_ZNSt12experimental10filesystem2v17__cxx114path14_M_split_cmptsEv". (I'm just doing so😂)

**Comment by yuxuanzhou97** [comment]
Oh sorry, this is not a boost issue. It seems related to the support of c++17 and the linking of "experimental::filesystem". Try google "_ZNSt12experimental10filesystem2v17__cxx114path14_M_split_cmptsEv". (I'm just doing so😂)

**Comment by bobododosjl** [comment]
thank u，but I still not find solution to this error



---Original---
From: "Zhou ***@***.***&gt;
Date: Wed, May 1, 2024 22:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [GREAT-WHU/DBA-Fusion] Hi, I follow the instruction, and I meetthe following errors. (Issue #1)




 
Oh sorry, this is not a boost issue. It seems related to the support of c++17 and the linking of "experimental::filesystem". Try google "_ZNSt12experimental10filesystem2v17__cxx114path14_M_split_cmptsEv". (I'm just doing so😂)

**Comment by yuxuanzhou97** [comment]
We use CMake 3.21.5 and gcc 9.4.0 to build the gtsam library. Maybe update the CMake/gcc version and rebuild the library could help. 

Also see https://github.com/borglab/gtsam/issues/1495 which might provide a solution.

**Comment by yuxuanzhou97** [comment]
Btw, we use Ubuntu 20.04😂. And it could lead to some differences (like the default compiler) if you are using a different system version. Would you please provide more information about your environment?

**Comment by bobododosjl** [comment]
My os is ubuntu18.04, have same cmake version and gcc version

**Comment by bobododosjl** [comment]
problem solved

**Comment by bobododosjl** [comment]
Great work,if this point clouds map could be reused for place recognition?

**Comment by yuxuanzhou97** [comment]
I believe it is completely possible. I have been working on this.

**Comment by bobododosjl** [comment]
how to visualize point cloud?I don't see pcd format files.

**Comment by yuxuanzhou97** [comment]
The point clouds (and poses) are saved in the .pkl file. See the scripts in "visualization" folder for visualization.

**Comment by bobododosjl** [comment]
Thank u
