### ISSUE TITLE
If I want to get the pcd format of point clouds, how to deal with the results of your methods?

### ISSUE THREAD

**Issue by bobododosjl** [GREAT-WHU/DBA-Fusion#2]

**Comment by yuxuanzhou97** [comment]
See the scripts in "visualization" to load the .pkl file and use the Open3d api (https://stackoverflow.com/questions/60560878/how-can-i-output-the-open3d-geometry-pointcloud-as-pcd-file) to save the point clouds to .pcd file.

**Comment by bobododosjl** [comment]
THANK U
