### ISSUE TITLE
可以请教一个问题吗？你们如何用3DGS渲染的点云图呢？需要用COLMAP吗？

### ISSUE THREAD

**Issue by bobododosjl** [GREAT-WHU/DBA-Fusion#4]

**Comment by yuxuanzhou97** [comment]
不需要colmap，有了位姿和三维点云之后，理论上就不需要做SfM了。
但是需要改一些3D GS的输入接口，需要看一下3D GS的代码

**Comment by bobododosjl** [comment]
你们用3DGS渲染用的什么卡呢？4080，16GB显存可以不。

**Comment by yuxuanzhou97** [comment]
> 你们用3DGS渲染用的什么卡呢？4080，16GB显存可以不。

完全可以哇，我是用笔记本的4080，12g的

**Comment by bobododosjl** [comment]
多谢
