### ISSUE TITLE
你好，有尝试过整个点云地图的3DGS渲染吗？

### ISSUE THREAD

**Issue by bobododosjl** [GREAT-WHU/DBA-Fusion#5]

**Comment by yuxuanzhou97** [comment]
没有尝试过，只尝试了一段。我感觉应该可以整个点云，但是用原版的3DGS可能占显存非常大

**Comment by bobododosjl** [comment]
有试过将street gaussians用在你们数据上吗？

**Comment by yuxuanzhou97** [comment]
目前还没有尝试过，我目测是OK的。street gaussian支持SfM初始化GS或者LiDAR初始化GS，用本项目输出的点云应该也可以用来初始化

**Comment by yuxuanzhou97** [comment]
不过street gaussian的文章中的sequence也只有100帧，要做大尺度可能还是得考虑别的方案
